[package]
name = "esplugin-ffi"
version = "1.0.3"
authors = ["Oliver Hamlet <oliver.hamlet@gmail.com>"]
build = "build.rs"
description = "A wrapper library providing a C FFI for esplugin."
documentation = "https://docs.rs/esplugin-ffi"
repository = "https://github.com/WrinklyNinja/esplugin.git"
readme = "../README.md"
categories = ["games", "parsing"]
license = "GPL-3.0"
exclude = [
    "build/*",
    "include/*",
    "target/*",
]

[dependencies]
esplugin = { path = ".." }
libc = "0.2"

[lib]
crate-type = ["staticlib"]

[features]
default = []
ffi-headers = ["cbindgen"]

[build-dependencies]
cbindgen = { version = "0.1.14", optional = true }
