[package]
name = "esplugin-ffi"
version = "0.1.0"
authors = ["Oliver Hamlet <oliver.hamlet@gmail.com>"]
build = "build.rs"

[dependencies]
esplugin = { path = ".." }
libc = "*"

[lib]
crate-type = ["staticlib"]

[features]
default = []
ffi-headers = ["cbindgen"]

[build-dependencies]
cbindgen = { version = "0.1.14", optional = true }
