language = "C"
header = """
struct Plugin;
struct FormId;
"""
trailer = """
#ifdef __cplusplus
extern "C" {
#endif

extern uint32_t ESP_OK;
extern uint32_t ESP_OK;
extern uint32_t ESP_ERROR_NULL_POINTER;
extern uint32_t ESP_ERROR_NOT_UTF8;
extern uint32_t ESP_ERROR_STRING_CONTAINS_NUL;
extern uint32_t ESP_ERROR_INVALID_GAME_ID;
extern uint32_t ESP_ERROR_PARSE_ERROR;

extern uint32_t ESP_GAME_OBLIVION;
extern uint32_t ESP_GAME_SKYRIM;
extern uint32_t ESP_GAME_FALLOUT3;
extern uint32_t ESP_GAME_FALLOUTNV;
extern uint32_t ESP_GAME_MORROWIND;
extern uint32_t ESP_GAME_FALLOUT4;
extern uint32_t ESP_GAME_SKYRIMSE;

#ifdef __cplusplus
}
#endif
"""

[parse]
parse_deps = false
