language: rust

cache: cargo

install:
  - rustup component add rustfmt
  - rustfmt --version
  - curl -fsSL https://github.com/xd009642/tarpaulin/releases/download/0.8.6/cargo-tarpaulin-0.8.6-travis.tar.gz | tar xz
  - mv cargo-tarpaulin ~/.cargo/bin/

before_script:
  - wget https://github.com/Ortham/testing-plugins/archive/1.4.0.tar.gz
  - tar -xf 1.4.0.tar.gz
  - mv testing-plugins-1.4.0 testing-plugins

script:
  - cargo fmt --all -- --check
  - cargo test --all --all-features
  # Running cbindgen through tarpaulin fails due to an unexpected "metadata"
  # argument when generating the C header file, so skip the ffi-headers feature.
  - cargo tarpaulin --all --features compressed-fields --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  # Need to rebuild the FFI wrapper so that its binary is given a filename
  # without a hash.
  - cargo build --manifest-path ffi/Cargo.toml --features ffi-headers
  - mkdir ffi/build
  - cd ffi/build
  - cmake ..
  - make
  - make test
