sudo: required
language: rust

# Dependencies of tarpaulin
addons:
  apt:
    packages:
      - libssl-dev

cache: cargo

install:
  - rustup component add rustfmt-preview
  - rustfmt --version
  - |
    if [[ $(cargo tarpaulin --version) != *0.6.1 ]]
    then
      bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/0.6.1/travis-install.sh)
    fi

before_script:
  - wget https://github.com/WrinklyNinja/testing-plugins/archive/1.4.0.tar.gz
  - tar -xf 1.4.0.tar.gz
  - mv testing-plugins-1.4.0 testing-plugins

script:
  - cargo fmt --all -- --write-mode=diff
  - cargo test --all --all-features
  - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  # Need to rebuild the FFI wrapper so that its binary is given a filename
  # without a hash.
  - cargo build --manifest-path ffi/Cargo.toml --features ffi-headers
  - mkdir ffi/build
  - cd ffi/build
  - cmake ..
  - make
  - make test
