sudo: false
language: rust

# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

cache: cargo

install:
  - cargo install rustfmt || true
  - cargo install cargo-travis || true

before_script:
  - wget https://github.com/WrinklyNinja/testing-plugins/archive/1.2.0.tar.gz
  - tar -xf 1.2.0.tar.gz
  - mv testing-plugins-1.2.0 testing-plugins

script:
  - cargo fmt --all -- --write-mode=diff
  - cargo test --all --all-features
  - cargo coveralls -p libespm
  # Need to rebuild the FFI wrapper so that its binary is given a filename
  # without a hash.
  - cargo build -p libespm-ffi
  - python ffi/tests/ffi.py
