[package]
name = "libespm"
version = "0.1.0"
authors = ["Oliver Hamlet <oliver.hamlet@gmail.com>"]

[dependencies]
byteorder = "1.0.0"
encoding = "0.2.33"
libc = "*"
memmap = "0.5.2"
nom = "^2.2"
flate2 = { version = "0.2", optional = true }

[lib]
name = "espm"

[features]
default = []
compressed-fields = ["flate2"]

[workspace]
members = ["ffi"]
