[package]
name = "libespm"
version = "0.1.0"
authors = ["Oliver Hamlet <oliver.hamlet@gmail.com>"]
build = "build.rs"

[dependencies]
byteorder = "1.0.0"
encoding = "0.2.33"
flate2 = "0.2"
libc = "*"
memmap = "0.5.2"
nom = "^2.2"
clippy = {version = "*", optional = true}

[lib]
name = "espm"
crate-type = ["lib", "cdylib"]

[features]
default = []

[build-dependencies]
cbindgen = "0.1.13"
