[package]
name = "esplugin"
version = "1.0.0"
authors = ["Oliver Hamlet <oliver.hamlet@gmail.com>"]
description = "A free software library for reading Elder Scrolls plugin (.esp/.esm/.esl) files."
documentation = "https://docs.rs/esplugin"
repository = "https://github.com/WrinklyNinja/esplugin.git"
readme = "README.md"
categories = ["games", "parsing"]
license = "GPL-3.0"

[badges]
travis-ci = { repository = "WrinklyNinja/esplugin" }
coveralls = { repository = "WrinklyNinja/esplugin" }

[dependencies]
byteorder = "1.0.0"
encoding = "0.2.33"
memmap = "0.5.2"
nom = "^2.2"
unicase = "2.0.0"
flate2 = { version = "0.2", optional = true }

[features]
default = []
compressed-fields = ["flate2"]

[workspace]
members = ["ffi"]
